dashboard with cards and searchbar
nujovich/kurojam-sparta pull request #18
Opened 2023-08-17 21:39 UTC by juanmeyer94

## Info / Context

- The dashboard has been created, including the cards component and the navbar with search bar.

## Changes

-  Remove the standard HTML components of the Vite app and add the new components.
- Add the search bar and the cards to the "components" folder.

## How do you feel about this PR? (GIF)

![giphy](https://github.com/nujovich/kurojam-sparta/assets/107147413/290c1dac-fab5-49af-9ccf-94608677a283)

2023-08-18 05:19 UTC, nujovich requested changes

2023-08-18 05:19 UTC, nujovich commented on apps/client/src/components/cloudinary/UploadWidget.jsx
> +          //this.props.handleImageId(result.info.public_id);
Borrar comentario!

2023-08-18 07:15 UTC, cesmunoz commented on apps/client/package.json
> +    "@uploadthing/solid": "^5.1.2",
Si no vamos a usar uploadthing creo que podemos borrarlo

2023-08-18 07:16 UTC, cesmunoz commented on apps/client/src/components/serachbar/SearchBar.jsx
> +    }
Se puede borrar esta funcion?

2023-08-18 07:17 UTC, cesmunoz approved these changes
Deje unos pequeños comentarios pero lo veo bien!
Buen trabajo!

2023-08-19 13:22 UTC, juanmeyer94 commented on apps/client/src/components/cloudinary/UploadWidget.jsx
> +          //this.props.handleImageId(result.info.public_id);
Arreglado!! 💪

2023-08-19 14:45 UTC, merged